name: Update kodinerds samples

on:
  workflow_dispatch:
  schedule:
    - cron: '0 23 * * 2'

jobs:
  update_kodinerds:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Build tools
        run: |
          make 
          cd src/convm3u
          ./convert_all_kodinerds_streams.sh

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          commit-message: Update Kodinerds samples
          branch: bot-update-kodinerds
          delete-branch: true
          title: '[Bot] Update kodinerds channels'
          labels: |
            automated pull request
          draft: false